version: '2'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/root/.virtualenvs/snowplow-python-tracker/bin/pytest"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
